 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/member/posts", type: :request do
  # Member::Post. As you add validations to Member::Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Member::Post.create! valid_attributes
      get member_posts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      post = Member::Post.create! valid_attributes
      get member_post_url(member_post)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_member_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      post = Member::Post.create! valid_attributes
      get edit_member_post_url(member_post)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Member::Post" do
        expect {
          post member_posts_url, params: { member_post: valid_attributes }
        }.to change(Member::Post, :count).by(1)
      end

      it "redirects to the created member_post" do
        post member_posts_url, params: { member_post: valid_attributes }
        expect(response).to redirect_to(member_post_url(@member_post))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Member::Post" do
        expect {
          post member_posts_url, params: { member_post: invalid_attributes }
        }.to change(Member::Post, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post member_posts_url, params: { member_post: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested member_post" do
        post = Member::Post.create! valid_attributes
        patch member_post_url(member_post), params: { member_post: new_attributes }
        post.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the member_post" do
        post = Member::Post.create! valid_attributes
        patch member_post_url(member_post), params: { member_post: new_attributes }
        post.reload
        expect(response).to redirect_to(member_post_url(post))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        post = Member::Post.create! valid_attributes
        patch member_post_url(member_post), params: { member_post: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested member_post" do
      post = Member::Post.create! valid_attributes
      expect {
        delete member_post_url(member_post)
      }.to change(Member::Post, :count).by(-1)
    end

    it "redirects to the member_posts list" do
      post = Member::Post.create! valid_attributes
      delete member_post_url(member_post)
      expect(response).to redirect_to(member_posts_url)
    end
  end
end
